_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -102.4805
  - 45.8288
  - 2
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 14
minzoom: 0
name: ''
source: "mapbox:///mapbox.mapbox-streets-v5,iwsstuart.c4c1988b,iwsstuart.f5b88312"
styles: 
  - style.mss
template: ''
