styles: 
  - style.mss
sources: 
  - mapbox://mapbox.mapbox-streets-v3
name: ""
description: ""
attribution: "Map data © OpenStreetMap contributors"
mtime: 1366650077722
center: 
  - 0
  - 20
  - 3
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
minzoom: 0
maxzoom: 22
scale: 1
_prefs: 
  saveCenter: true
