_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -122.4976
  - 37.5881
  - 6
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 16
minzoom: 0
name: Street Art
source: "mapbox:///mapbox.mapbox-streets-v5,iwsstuart.c4c1988b,iwsstuart.f5b88312"
styles: 
  - style.mss
template: ''
